CREATE TABLE `ttt` (
  `a1` bigint(20) DEFAULT NULL,
  `a2` binary(1) DEFAULT NULL,
  `a3` binary(1) DEFAULT NULL,
  `a4` blob,
  `a5` tinyint(1) DEFAULT NULL,
  `a6` tinyint(1) DEFAULT NULL,
  `a7` tinyint(1) DEFAULT NULL,
  `a8` char(1) DEFAULT NULL,
  `a9` date DEFAULT NULL,
  `a10` datetime DEFAULT NULL,
  `a11` double DEFAULT NULL,
  `a12` enum('1') DEFAULT NULL,
  `a13` float DEFAULT NULL,
  `a14` int(11) DEFAULT NULL,
  `a15` longblob,
  `a16` longtext,
  `a17` mediumblob,
  `a18` mediumint(9) DEFAULT NULL,
  `a19` mediumtext,
  `a20` decimal(10,0) DEFAULT NULL,
  `a21` double DEFAULT NULL,
  `a22` set('a') DEFAULT NULL,
  `a23` smallint(6) DEFAULT NULL,
  `a24` text,
  `a25` time DEFAULT NULL,
  `a26` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  `a27` tinyblob,
  `a28` tinyint(4) DEFAULT NULL,
  `a29` tinytext,
  `a30` varbinary(1) DEFAULT NULL,
  `a31` varchar(1) DEFAULT NULL,
  `a32` year(4) DEFAULT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8